version: '2'
services:
  django:
    build:
      context: ./src/django
      dockerfile: Dockerfile
    environment:
      - PGHOST=database.service.pfb.internal
      - PGDATABASE=pfb
      - PGPASSWORD=pfb
      - PGPORT=5432
      - PGUSER=pfb
      - DJANGO_ENV=development
      - DJANGO_SECRET_KEY=secret
      - DJANGO_LOG_LEVEL=INFO
      - AWS_PROFILE=pfb
      - PFB_AWS_BATCH_COMPUTE_ENVIRONMENT_ARN
      - PFB_AWS_BATCH_JOB_QUEUE_NAME
      - PFB_AWS_BATCH_JOB_DEFINITION_NAME_REVISION
      - PFB_AWS_BATCH_JOB_DEFINITION_NAME
    volumes:
      - ./data:/data
      - ./src/django:/usr/src
      - ./src/nginx/srv/static:/static/
      - $HOME/.aws:/root/.aws:ro
