version: '2'
services:
  database:
    image: quay.io/azavea/postgis:postgres9.6-postgis2.3
    environment:
      - POSTGRES_USER=pfb
      - POSTGRES_PASSWORD=pfb
      - POSTGRES_DB=pfb

  nginx:
    image: pfb-nginx
    build:
      context: ./src/nginx
      dockerfile: Dockerfile
    ports:
      - "9200:443"
    links:
      - django
    volumes:
      - ./src/nginx/srv/dist:/srv/dist:ro

  django:
    image: pfb-django
    extends:
      service: django
      file: common.yml
    ports:
      - "9202:9202"
      - "9203:9203"
    links:
      - database:database.service.pfb.internal
    environment:
      - DEV_USER

# TODO: Re-add this container once the SQS broker is setup (issue #20)
  # celery:
  #   image: pfb-django
  #   extends:
  #     service: celery
  #     file: common.yml
  #   links:
  #     - database:database.service.pfb.internal

  angularjs:
    image: pfb-angularjs
    working_dir: /opt/pfb/angular
    build:
      context: ./src/angularjs
      dockerfile: Dockerfile
    links:
      - nginx:pfb.internal
    ports:
      - "9301:9301"
      - "9302:9302"
    volumes:
      - ./src/angularjs/.eslintrc:/opt/pfb/angular/.eslintrc
      - ./src/angularjs/gulp:/opt/pfb/angular/gulp
      - ./src/angularjs/gulpfile.js:/opt/pfb/angular/gulpfile.js
      - ./src/angularjs/src:/opt/pfb/angular/src
      - ./src/angularjs/docs:/opt/pfb/angular/docs
    command: gulp serve
