version: '2'
services:
  database:
    image: quay.io/azavea/postgis:postgres9.6-postgis2.3
    environment:
      - POSTGRES_USER=pfb
      - POSTGRES_PASSWORD=pfb
      - POSTGRES_DB=pfb

  nginx:
    image: pfb-nginx
    build:
      context: ./src/nginx
      dockerfile: Dockerfile
    ports:
      - "9200:443"
    links:
      - django

  django:
    image: pfb-app
    extends:
      service: django
      file: common.yml
    ports:
      - "9202:9202"
      - "9203:9203"
    links:
      - database:database.service.pfb.internal
    environment:
      - DEV_USER

  angularjs:
    image: pfb-angularjs
    working_dir: /opt/pfb/angularjs
    build:
      context: ./src/angularjs
      dockerfile: Dockerfile
    links:
      - nginx:pfb.internal
    ports:
      - "9301:9301"
      - "9302:9302"
    volumes:
      - ./src/angularjs/.eslintrc:/opt/pfb/angularjs/.eslintrc
      - ./src/angularjs/gulp:/opt/pfb/angularjs/gulp
      - ./src/angularjs/gulpfile.js:/opt/pfb/angularjs/gulpfile.js
      - ./src/angularjs/src:/opt/pfb/angularjs/src
      - ./src/angularjs/docs:/opt/pfb/angularjs/docs
    command: gulp serve

  analysis:
    image: pfb-analysis
    extends:
      service: django
      file: common.yml
    build:
      context: .
      dockerfile: pfb-analysis/Dockerfile
    links:
      - database:database.service.pfb.internal
    volumes:
      - ./data:/data
      - /home/vagrant/.aws:/root/.aws
      - ./src/django:/opt/pfb/django
    environment:
      - PFB_AWS_BATCH_COMPUTE_ENVIRONMENT_ARN
      - PFB_AWS_BATCH_JOB_QUEUE_NAME
      - PFB_AWS_BATCH_JOB_DEFINITION_NAME_REVISION
      - PFB_AWS_BATCH_JOB_DEFINITION_NAME
