version: '2'
services:
  update-job-defs:
      image: update-job-defs
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - AWS_PROFILE=pfb
      volumes:
        - $HOME/.aws:/root/.aws:ro
