rules:
    property-sort-order: 0
    mixins-before-declarations: 0
    indentation: 0
    no-important: 0
    no-color-literals: 0
    quotes: 0
    no-css-comments: 0
    single-line-per-selector: 0
    pseudo-element: 0
    no-trailing-whitespace: 0
    space-around-operator: 0
    attribute-quotes: 0
    empty-line-between-blocks: 0
    force-pseudo-nesting: 0
    no-vendor-prefixes: 0
    leading-zero: 0
    no-qualifying-elements: 0
    no-color-keywords: 0
    zero-unit: 0
    border-zero: 0
    hex-notation: 0
    hex-length: 0
    brace-style: 0
    no-empty-rulesets: 0
    force-element-nesting: 0
    placeholder-in-extend: 0
    force-attribute-nesting: 0
    final-newline: 0
    space-after-comma: 0
    no-duplicate-properties: 0
    trailing-semicolon: 0
    no-ids: 0
    class-name-format: 0
    url-quotes: 0
    shorthand-values: 0
    no-warn: 0
