_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -111.0526
  - 40.5242
  - 11
description: Show bike infrastructure of interest
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 16
minzoom: 8
name: Bike Infrastructure
source: "tmsource:///Users/andrew/src/pfb-network-connectivity/src/tilemaker/working_files/combined_data.tm2source"
styles: 
  - bike_infrastructure.mss
template: ''
