_prefs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -112.2267
  - 33.5514
  - 12
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Combined styles - Glendale
source: "tmsource:///home/local/AZVA-INT/khoekema/projects/pfb/pfb-network-connectivity/src/tilemaker/working_files/combined_data.tm2source"
styles: 
  - census_blocks.mss
  - ways.mss
template: ''
