_prefs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -111.0903
  - 40.5177
  - 11
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 17
minzoom: 8
name: Combined Styles - Fort Collins, CO
source: "tmsource:///Users/andrew/src/pfb-network-connectivity/src/tilemaker/working_files/combined_data.tm2source"
styles: 
  - census_blocks.mss
  - ways.mss
  - bike_infrastructure.mss
template: ''
