_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -111.0659
  - 40.5562
  - 12
description: Color census blocks based on overall bike network score
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 16
minzoom: 8
name: Census Blocks
source: "tmsource:///Users/andrew/src/pfb-network-connectivity/src/tilemaker/working_files/combined_data.tm2source"
styles: 
  - census_blocks.mss
template: ''
