_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -111.0526
  - 40.5345
  - 12
description: Color road segments based on bike stress
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 16
minzoom: 8
name: Neighborhood Ways
source: "tmsource:///Users/andrew/src/pfb-network-connectivity/src/tilemaker/working_files/combined_data.tm2source"
styles: 
  - neighborhood_ways.mss
template: ''
