---

- name: Download TDG Tools extension from GitHub
  git: repo=https://github.com/spencerrecneps/TDG-Tools.git
       dest="{{ tdgtools_src_dir }}"
       version="{{ tdgtools_git_tag }}"
       force=yes
       accept_hostkey=true

- name: Clean TDG Tools dir
  command: make clean
  args:
    chdir: "{{ tdgtools_src_dir }}/TDG\ SQL\ Tools"
    creates: "/usr/share/postgresql/{{ postgresql_version }}/extension/tdg.control"

- name: Install TDG Tools extension
  command: make install
  args:
    chdir: "{{ tdgtools_src_dir }}/TDG\ SQL\ Tools"
    creates: "/usr/share/postgresql/{{ postgresql_version }}/extension/tdg.control"

- name: Add tdg extension to PFB database
  become_user: postgres
  postgresql_ext: name=tdg db="{{ postgresql_database_name }}"
