---

- name: Install osm2pgrouting build dependencies
  apt: name={{ item }}
  with_items:
    - expat
    - libexpat1-dev
    - cmake
    - libboost-all-dev

- name: Download osm2pgrouting from GitHub
  git: repo=https://github.com/pgRouting/osm2pgrouting.git
       dest="{{ osm2pgrouting_src_dir }}"
       version="{{ osm2pgrouting_git_tag }}"
       accept_hostkey=true

- name: Create osm2pgrouting build dir
  file: path="{{ osm2pgrouting_src_dir }}/build" state=directory

- name: Run osm2pgrouting cmake
  command: cmake -H. -Bbuild
  args:
   chdir: "{{ osm2pgrouting_src_dir }}"
   creates: /usr/bin/osm2pgrouting

- name: Run osm2pgrouting make
  command: make
  args:
    chdir: "{{ osm2pgrouting_src_dir }}/build"
    creates: /usr/bin/osm2pgrouting

- name: Run osm2pgrouting make install
  command: make install
  args:
    chdir: "{{ osm2pgrouting_src_dir }}/build"
    creates: /usr/bin/osm2pgrouting
