---

- name: Download quantile extension from GitHub
  git: repo=https://github.com/tvondra/quantile.git
       dest="{{ quantile_src_dir }}"
       version="{{ quantile_git_tag }}"
       force=yes
       accept_hostkey=true

- name: Install quantile extension
  command: make install
  args:
    chdir: "{{ quantile_src_dir }}"
    creates: "/usr/share/postgresql/{{ postgresql_version }}/extension/quantile.control"

- name: Add quantile extension to PFB database
  become_user: postgres
  postgresql_ext: name=quantile db="{{ postgresql_database_name }}"
