---
- hosts: all
  become: true

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.aws-cli" }
    - { role: "azavea.terraform" }
    - { role: "pfb.env" }
    - { role: "pfb.docker" }
